[tool.poetry]
name = "nonebot-plugin-styledstr"
version = "0.1.1"
description = "A Styled String Managing Plugin for Nonebot 2"
authors = ["Satoshi Jek <jks15satoshi@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^5.4.1"
nonebot2 = "^2.0.0-alpha.8"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
